#!/usr/bin/python
import sys
import parser

from syntax import *

count = int(sys.argv[1])
body = open(sys.argv[2]).read()
tree = parser.parse(body)
expr = `tree`
if expr <> `eval(expr)`:
	print "Expression doesn't evaluate back to itself!"
	sys.exit(1)
for i in range(count):
	eval(expr)
