#!/usr/bin/python
import sys
import parser

try:
	(argv0,filename) = sys.argv
except:
	print "usage: %s filename" % sys.argv[0]
	sys.exit(1)

body = open(filename).read()
tree = parser.parse(body)
tree.showtree(0)
